### ISSUE TITLE
Country_Code

### ISSUE THREAD

**Issue by SadraSalman** [joshsmith/worldwide-city-database#3]
Sorry to bother u again
what is exactly country_code , i mean countries like united states got States which u mentioned them in combined but in other countries like France what is the number which represents country_code ? 
thanks.

**Comment by yatish63** [comment]
SadraSalman, country_code represents the two letter code for a country.
ref : http://www.worldatlas.com/aatlas/ctycodes.htm

**Comment by joshsmith** [comment]
Thanks @yatish63
